export const environment = {
    production: false,
    apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNThjZDdhNC0wM2Q0LTRkM2ItYmJiNi1jZTk0ZjY0YjY2YzAiLCJlbWFpbCI6InBhb2xhU2lsdmFPbGl2ZWlyYUBnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiUGFvbGEgT2xpdmVpcmEiLCJuYmYiOjE2OTcyMjAzNzAsImV4cCI6MTY5NzI0OTE3MCwiaWF0IjoxNjk3MjIwMzcwLCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.hOsoHvKyOaEu-cACJsjvGyxZN4I74lNCglvukZfv6KM'
};
